spring:
  application:
    name: learn-spring-ai
  ai: #https://ai.google.dev/gemini-api/docs/openai
    openai:
      api-key: ${GOOGLE_AI_API_KEY}
      base-url: https://generativelanguage.googleapis.com
      chat:
        options:
          model: gemini-2.0-flash
        completions-path: /v1beta/openai/chat/completions
      image:
        options:
          model: imagen-3.0-generate-002
        images-path: /v1beta/openai/images/generations
      audio:
        speech:
          options:
            model:
          base-url: 

logging:
  level:
    org.springframework.ai: TRACE
    org.springframework.http: TRACE
    org.springframework.web.client: TRACE
    org.apache.hc.client5.http: TRACE
