spring:
  application:
    name: learn-spring-ai
  ai:
    openai:
      api-key: ${GOOGLE_AI_API_KEY}
      base-url: https://generativelanguage.googleapis.com
      chat:
        options:
          model: gemini-2.0-flash
        completions-path: /v1beta/openai/chat/completions

logging:
  level:
    org.springframework.ai: TRACE
    org.springframework.http: TRACE
    org.springframework.web.client: TRACE
    jdk.internal.net.http: TRACE
    jdk.net: TRACE
